name: Build the game
on: push
jobs:
  create_executable_file:
    name: Create the executable file.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the executable file.
        run: ./gradlew lwjgl3:dist
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          path: core/build/libs
