name: Build game
on: release
jobs:
  create_executable_file:
    name: Create executable file.
    runs-on: ubuntu-latest
    steps:
      - name: Build executable file.
        run: echo "::error This is error!"
