name: Build the game
on: push
jobs:
  create_executable_file:
    name: Create the executable file.
    runs-on: ubuntu-latest
    steps:
      - name: Build the executable file.
        run: './gradlew lwjgl3:dist'
