name: Generate release
on:
  release:
    types:
      - released

permissions:
  contents: write

env:
  GH_TOKEN: $GITHUB_TOKEN

jobs:
  upload_project_to_release:
    name: Upload the project to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Change project version in gradle
        run: sed -i "/projectVersion=dev/projectVersion=$GITHUB_REF_NAME/" gradle.properties
      - name: Build the executable file
        run: ./gradlew lwjgl3:dist
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: lwjgl3/build/libs/*.jar
