name: Generate release.
on:
  release:
    types:
      - released

jobs:
  create_executable_file_for_ubuntu:
    name: Create the executable file.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the executable file.
        run: ./gradlew lwjgl3:dist
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: crazyrocket-ubuntu
          path: dist/
  upload_file_to_release:
    name: Upload the file to release
    needs: create_executable_file_for_ubuntu
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: $GITHUB_TOKEN
    steps:
      - name: Copy file
        run: gh release edit v0.1 --notes-file dist/
